import gc
import logging
import os
import shutil
import tempfile
from pathlib import Path
from typing import List, Optional
import numpy as np

# Compatibility patch for audio-separator with newer librosa versions (librosa 1.x changed filename -> path)
try:
    import librosa
    _orig_get_duration = librosa.get_duration
    def _compat_get_duration(*args, **kwargs):
        if "filename" in kwargs:
            kwargs["path"] = kwargs.pop("filename")
        return _orig_get_duration(*args, **kwargs)
    librosa.get_duration = _compat_get_duration
except Exception:
    pass

from inst_splitter.audio_io import load_audio_as_stereo_pcm, save_24bit_wav
from inst_splitter.separator.base import SeparatorBackend
from inst_splitter.utils import setup_logger

logger = setup_logger("audio_separator_backend")

# Common model alias mapping for audio-separator
MODEL_ALIASES = {
    "htdemucs_ft": "htdemucs_ft.yaml",
    "htdemucs": "htdemucs.yaml",
    "mdx_extra": "htdemucs.yaml",
    "hdemucs_mmi": "hdemucs_mmi.yaml",
    "htdemucs_6s": "htdemucs_6s.yaml",
}


class AudioSeparatorBackend(SeparatorBackend):
    """
    Stem separation backend wrapping python-audio-separator.
    Loads and runs models sequentially with memory unloading.
    Supports 2-stem models as well as 4-stem Demucs models (Drums + Bass + Other summing).
    """

    def __init__(self, output_dir: Optional[str] = None, model_file_dir: Optional[str] = None):
        super().__init__(output_dir=output_dir)
        self.model_file_dir = model_file_dir
        self.separator = None
        self._temp_dir = None

    def load_model(self, model_name: str, **kwargs) -> None:
        """Initialize Separator and load specific model."""
        self.unload_model()

        try:
            from audio_separator.separator import Separator
        except ImportError as e:
            raise ImportError(
                "audio-separator package is not installed. Please install it with `pip install audio-separator`."
            ) from e

        # Resolve alias if needed
        resolved_name = MODEL_ALIASES.get(model_name, model_name)

        import logging
        self._temp_dir = tempfile.mkdtemp(prefix="inst_separator_")
        self.separator = Separator(
            output_dir=self._temp_dir,
            model_file_dir=self.model_file_dir or os.path.expanduser("~/.cache/audio-separator-models"),
            output_format="wav",
            log_level=logging.WARNING,
            **kwargs,
        )

        logger.debug(f"Loading model: {resolved_name} (original: {model_name})")
        self.separator.load_model(model_filename=resolved_name)
        self.current_model_name = resolved_name

    def separate_instrumental(self, audio_pcm: np.ndarray, sr: int = 44100) -> np.ndarray:
        """
        Separate audio and return instrumental stem as stereo float32 PCM of shape (2, N).
        If 4-stem output is produced (e.g. Demucs), sums all non-vocal stems (Drums + Bass + Other).
        """
        if self.separator is None or self.current_model_name is None:
            raise RuntimeError("No model is loaded. Call load_model() first.")

        # Write input PCM to temporary WAV for separator
        temp_input_wav = Path(self._temp_dir) / "input_temp.wav"
        save_24bit_wav(temp_input_wav, audio_pcm, sr=sr)

        try:
            output_files = self.separator.separate(str(temp_input_wav))
            logger.info(f"Separation output files from {self.current_model_name}: {output_files}")

            if not output_files:
                raise RuntimeError(f"Separation failed: no output files generated by {self.current_model_name}")

            resolved_files = [
                Path(self._temp_dir) / out_f if not os.path.isabs(out_f) else Path(out_f)
                for out_f in output_files
            ]

            # 1. Check for single explicit instrumental / accompaniment stem
            inst_file = None
            for out_path in resolved_files:
                stem_lower = out_path.stem.lower()
                if (
                    "(instrumental)" in stem_lower
                    or "_(instrumental)" in stem_lower
                    or "(no_vocals)" in stem_lower
                    or "(accompaniment)" in stem_lower
                    or "(other)" in stem_lower and len(resolved_files) <= 2
                    or "(backing" in stem_lower
                ):
                    inst_file = out_path
                    break

            if inst_file is not None and inst_file.exists():
                logger.info(f"Selected single instrumental stem file: {inst_file.name}")
                inst_pcm, _ = load_audio_as_stereo_pcm(inst_file, target_sr=sr)
                return inst_pcm

            # 2. Multi-stem Demucs handling (e.g., Drums, Bass, Other, Vocals)
            non_vocal_files: List[Path] = []
            for out_path in resolved_files:
                stem_lower = out_path.stem.lower()
                is_vocal = (
                    "(vocal" in stem_lower
                    or "_(vocal" in stem_lower
                    or "(lead" in stem_lower
                    or "(vocals)" in stem_lower
                )
                if not is_vocal and out_path.exists():
                    non_vocal_files.append(out_path)

            if non_vocal_files:
                if len(non_vocal_files) == 1:
                    logger.info(f"Selected non-vocal stem file: {non_vocal_files[0].name}")
                    inst_pcm, _ = load_audio_as_stereo_pcm(non_vocal_files[0], target_sr=sr)
                    return inst_pcm
                else:
                    # Sum multiple non-vocal stems (e.g. Drums + Bass + Other)
                    logger.info(
                        f"Summing {len(non_vocal_files)} non-vocal stems: {[f.name for f in non_vocal_files]}"
                    )
                    target_length = audio_pcm.shape[1]
                    combined_inst = np.zeros((2, target_length), dtype=np.float32)

                    for stem_f in non_vocal_files:
                        stem_pcm, _ = load_audio_as_stereo_pcm(stem_f, target_sr=sr)
                        cur_len = stem_pcm.shape[1]
                        if cur_len == target_length:
                            combined_inst += stem_pcm
                        elif cur_len > target_length:
                            combined_inst += stem_pcm[:, :target_length]
                        else:
                            combined_inst[:, :cur_len] += stem_pcm

                    return combined_inst

            # Fallback to last file if classification fails
            inst_file = resolved_files[-1]
            logger.warning(f"Fallback to last separation output file: {inst_file.name}")
            inst_pcm, _ = load_audio_as_stereo_pcm(inst_file, target_sr=sr)
            return inst_pcm

        finally:
            if temp_input_wav.exists():
                temp_input_wav.unlink(missing_ok=True)

    def unload_model(self) -> None:
        """Unload separator model and clean up temporary directory and memory."""
        if self.separator is not None:
            logger.debug(f"Unloading model: {self.current_model_name}")
            self.separator = None
            self.current_model_name = None

        if self._temp_dir and Path(self._temp_dir).exists():
            shutil.rmtree(self._temp_dir, ignore_errors=True)
            self._temp_dir = None

        # Clean memory caches
        gc.collect()
        try:
            import torch
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            if hasattr(torch, "mps") and hasattr(torch.mps, "empty_cache"):
                torch.mps.empty_cache()
        except ImportError:
            pass
